---
title: "La Fórmula 1"
subtitle: "Proyecto Final"
output: pdf_document
date: "Marzo de 2025"
fontsize: 12pt
lang: es-Mx
toc: TRUE
---

```{r setup, include=FALSE}

#inserción de data frame en Rstudio y llamado de librerias

library(tidyverse)
library(stringr)
library(stringi)
library(readr)
library(gt) 
library(dplyr)
library(knitr)
library(tinytex) 
library(readxl)
library(dplyr)
library(RSQLite)
library(DBI)
library(writexl)

# Conexión con data SQLite

con <- dbConnect(RSQLite::SQLite(), dbname = "Formula1.sqlite")
tablas <- dbListTables(con)
print(tablas)

# Query y creación de data frame

DfFormula1 <- dbReadTable(con, tablas[1]) 

corredores <-"SELECT * FROM drivers" 
dfcorredores <- dbGetQuery(con ,corredores) 

circuitos <-"SELECT * FROM circuits" 

DfCircutitos <- dbGetQuery(con, circuitos)

DfCircuitos <- dbReadTable(con, "circuits")

#Salida de archivo excel para toda la base de datos

lista_de_datos <- list()
for (tabla in tablas) {
  datos <- dbReadTable(con, tabla)
  lista_de_datos[[tabla]] <- datos
}
write_xlsx(lista_de_datos, "Formula1.xlsx")

# Cerrar la conexión a la base de datos
dbDisconnect(con)

```


```{r}
# Observar los mejores corredores del año 2017 en base a la suma de sus puntos y victorias

Mejores_en_2017 <- "
SELECT
    a.driverRef AS Referencia,
    a.forename AS Nombre,
    a.surname Apellido,
    a.number AS Número,
    d.year AS Año,
    SUM(b.points) AS TotalPuntos,
    sum(b.wins) AS TotalVictorias
FROM drivers a
INNER JOIN driver_standings b ON a.driverId = b.driverId
INNER JOIN races c ON b.raceId = c.raceId
INNER JOIN seasons d ON c.year = d.year
WHERE d.year = 2017
GROUP BY a.driverId
ORDER BY TotalPuntos DESC
LIMIT 5;
"
Mejores_2017 <- dbGetQuery(con, Mejores_en_2017)
```

```{r}
# Observar los mejores corredores del año 2016 en base a la suma de sus puntos y victorias

Mejores_en_2016 <- "
SELECT
    a.driverRef AS Referencia,
    a.forename AS Nombre,
    a.surname Apellido,
    a.number AS Número,
    d.year AS Año,
    SUM(b.points) AS TotalPuntos,
    sum(b.wins) AS TotalVictorias
FROM drivers a
INNER JOIN driver_standings b ON a.driverId = b.driverId
INNER JOIN races c ON b.raceId = c.raceId
INNER JOIN seasons d ON c.year = d.year
WHERE d.year = 2016
GROUP BY a.driverId
ORDER BY TotalPuntos DESC
LIMIT 5;
"
Mejores_2016 <- dbGetQuery(con, Mejores_en_2016)

```

```{r}
# Observar los mejores corredores del año 2015 en base a la suma de sus puntos y victorias

Mejores_en_2015 <- "
SELECT
    a.driverRef AS Referencia,
    a.forename AS Nombre,
    a.surname Apellido,
    a.number AS Número,
    d.year AS Año,
    SUM(b.points) AS TotalPuntos,
    sum(b.wins) AS TotalVictorias
FROM drivers a
INNER JOIN driver_standings b ON a.driverId = b.driverId
INNER JOIN races c ON b.raceId = c.raceId
INNER JOIN seasons d ON c.year = d.year
WHERE d.year = 2015
GROUP BY a.driverId
ORDER BY TotalPuntos DESC
LIMIT 5;
"

Mejores_2015 <- dbGetQuery(con, Mejores_en_2015)
```

```{r}
# Observar los mejores corredores del año 2014 en base a la suma de sus puntos y victorias

Mejores_en_2014 <- "
SELECT
    a.driverRef AS Referencia,
    a.forename AS Nombre,
    a.surname Apellido,
    a.number AS Número,
    d.year AS Año,
    SUM(b.points) AS TotalPuntos,
    sum(b.wins) AS TotalVictorias
FROM drivers a
INNER JOIN driver_standings b ON a.driverId = b.driverId
INNER JOIN races c ON b.raceId = c.raceId
INNER JOIN seasons d ON c.year = d.year
WHERE d.year = 2014
GROUP BY a.driverId
ORDER BY TotalPuntos DESC
LIMIT 5;
"

Mejores_2014 <- dbGetQuery(con, Mejores_en_2014)
```


```{r}
# Observar los mejores corredores del año 2013 en base a la suma de sus puntos y victorias

Mejores_en_2013 <- "
SELECT
    a.driverRef AS Referencia,
    a.forename AS Nombre,
    a.surname Apellido,
    a.number AS Número,
    d.year AS Año,
    SUM(b.points) AS TotalPuntos,
    sum(b.wins) AS TotalVictorias
FROM drivers a
INNER JOIN driver_standings b ON a.driverId = b.driverId
INNER JOIN races c ON b.raceId = c.raceId
INNER JOIN seasons d ON c.year = d.year
WHERE d.year = 2013
GROUP BY a.driverId
ORDER BY TotalPuntos DESC
LIMIT 5;
"

Mejores_2013 <- dbGetQuery(con, Mejores_en_2013)

#### DE ESTA FORMA OBTENEMOS EN TABLAS LOS 5 MEJORES CORREDORES DURANTE 2013 - 2017 ###
```

```{r}

#### MEJORES ESCUDERIAS EN BASE SUS PUNTOS Y VICTORIAS DURANTE 2017 - 2013 ####

### Mejores escuderias en 2017 ##

mejores_escuderias_2017 <- "SELECT
a.constructorId AS ID,
a.name AS Escuderia,
c.year AS Año,
SUM(b.points) AS TotalPuntos,
sum(b.wins) AS TotalVictorias
FROM constructors a
INNER JOIN constructor_standings b ON a.constructorId = b.constructorId
INNER JOIN races c ON c.raceId = b.raceId
WHERE c.year = 2017
GROUP BY a.constructorId
ORDER BY TotalPuntos DESC
LIMIT 5;"

Escuderias_2017 <- dbGetQuery(con, mejores_escuderias_2017)

```

```{r}
## Mejores escuderias en 2016 ##

mejores_escuderias_2016 <- "SELECT
a.constructorId AS ID,
a.name AS Escuderia,
c.year AS Año,
SUM(b.points) AS TotalPuntos,
sum(b.wins) AS TotalVictorias
FROM constructors a
INNER JOIN constructor_standings b ON a.constructorId = b.constructorId
INNER JOIN races c ON c.raceId = b.raceId
WHERE c.year = 2016
GROUP BY a.constructorId
ORDER BY TotalPuntos DESC
LIMIT 5;"

Escuderias_2016 <- dbGetQuery(con, mejores_escuderias_2016)

```

```{r}

## Mejores escuderias en 2015 ##

mejores_escuderias_2015 <- "SELECT
a.constructorId AS ID,
a.name AS Escuderia,
c.year AS Año,
SUM(b.points) AS TotalPuntos,
sum(b.wins) AS TotalVictorias
FROM constructors a
INNER JOIN constructor_standings b ON a.constructorId = b.constructorId
INNER JOIN races c ON c.raceId = b.raceId
WHERE c.year = 2015
GROUP BY a.constructorId
ORDER BY TotalPuntos DESC
LIMIT 5;"

Escuderias_2015 <- dbGetQuery(con, mejores_escuderias_2015)
```

```{r}
## Mejores escuderias en 2014 ##

mejores_escuderias_2014 <- "SELECT
a.constructorId AS ID,
a.name AS Escuderia,
c.year AS Año,
SUM(b.points) AS TotalPuntos,
sum(b.wins) AS TotalVictorias
FROM constructors a
INNER JOIN constructor_standings b ON a.constructorId = b.constructorId
INNER JOIN races c ON c.raceId = b.raceId
WHERE c.year = 2014
GROUP BY a.constructorId
ORDER BY TotalPuntos DESC
LIMIT 5;"

Escuderias_2014 <- dbGetQuery(con, mejores_escuderias_2014)

```

```{r}
## Mejores escuderias en 2013 ##

mejores_escuderias_2013 <- "SELECT
a.constructorId AS ID,
a.name AS Escuderia,
c.year AS Año,
SUM(b.points) AS TotalPuntos,
sum(b.wins) AS TotalVictorias
FROM constructors a
INNER JOIN constructor_standings b ON a.constructorId = b.constructorId
INNER JOIN races c ON c.raceId = b.raceId
WHERE c.year = 2013
GROUP BY a.constructorId
ORDER BY TotalPuntos DESC
LIMIT 5;"

Escuderias_2013 <- dbGetQuery(con, mejores_escuderias_2013)

## DE ESTA FORMA OBTENEMOS LAS 5 MEJORES ESCUDERIAS DURANTE 2017 - 2013 ##
```

```{r}
## NUMERO DE VECES EN QUE CADA PILOTO HA TERMINADO ENTRE LOS TRES PRIMEROS ENTRE EL 2013 Y 2017 ##

## 2013 ##

Podios_2013 <- "SELECT d.driverId AS ID_Pilotos,
d.forename AS Nombre,
       d.surname AS Apellido,
       s.year AS temporada,   
       SUM(CASE WHEN r.position = 1 THEN 1 ELSE 0 END) AS Podios_1,
       SUM(CASE WHEN r.position = 2 THEN 1 ELSE 0 END) AS Podios_2,
       SUM(CASE WHEN r.position = 3 THEN 1 ELSE 0 END) AS Podios_3,
       COUNT(r.position) AS Cantidad_Podios
FROM  
       results r 
INNER JOIN 
       drivers d ON d.driverId = r.driverId
INNER JOIN 
     races s ON s.raceId = r.raceId
WHERE 
       r.position IN (1, 2, 3) AND
	   s.year = 2013
GROUP BY
       d.driverId, 
	   d.forename, d.surname
ORDER BY Cantidad_Podios DESC
LIMIT 3;"

Podios_2013 <- dbGetQuery(con, Podios_2013) 
```


```{r}
## 2014 ##

Podios_2014 <- "SELECT d.driverId AS ID_Pilotos,
       d.forename AS Nombre,
       d.surname AS Apellido,
       s.year AS temporada,   
       SUM(CASE WHEN r.position = 1 THEN 1 ELSE 0 END) AS Podios_1,
       SUM(CASE WHEN r.position = 2 THEN 1 ELSE 0 END) AS Podios_2,
       SUM(CASE WHEN r.position = 3 THEN 1 ELSE 0 END) AS Podios_3,
       COUNT(r.position) AS Cantidad_Podios
FROM  
       results r 
INNER JOIN 
       drivers d ON d.driverId = r.driverId
INNER JOIN 
     races s ON s.raceId = r.raceId
WHERE 
       r.position IN (1, 2, 3) AND
	   s.year = 2014
GROUP BY
       d.driverId, 
	   d.forename, d.surname
ORDER BY Cantidad_Podios DESC
LIMIT 3;"

Podios_2014 <- dbGetQuery(con, Podios_2014) 

```



```{r}
## 2015 ## 

Podios_2015 <- "SELECT d.driverId AS ID_Pilotos,
       d.forename AS Nombre,
       d.surname AS Apellido,
       s.year AS temporada,   
       SUM(CASE WHEN r.position = 1 THEN 1 ELSE 0 END) AS Podios_1,
       SUM(CASE WHEN r.position = 2 THEN 1 ELSE 0 END) AS Podios_2,
       SUM(CASE WHEN r.position = 3 THEN 1 ELSE 0 END) AS Podios_3,
       COUNT(r.position) AS Cantidad_Podios
FROM  
       results r 
INNER JOIN 
       drivers d ON d.driverId = r.driverId
INNER JOIN 
     races s ON s.raceId = r.raceId
WHERE 
       r.position IN (1, 2, 3) AND
	   s.year = 2015
GROUP BY
       d.driverId, 
	   d.forename, d.surname
ORDER BY Cantidad_Podios DESC
LIMIT 3;"

Podios_2015 <- dbGetQuery(con, Podios_2015) 

```


```{r}
## 2016 ## 

Podios_2016 <- "SELECT d.driverId AS ID_Pilotos,
       d.forename AS Nombre,
       d.surname AS Apellido,
       s.year AS temporada,   
       SUM(CASE WHEN r.position = 1 THEN 1 ELSE 0 END) AS Podios_1,
       SUM(CASE WHEN r.position = 2 THEN 1 ELSE 0 END) AS Podios_2,
       SUM(CASE WHEN r.position = 3 THEN 1 ELSE 0 END) AS Podios_3,
       COUNT(r.position) AS Cantidad_Podios
FROM  
       results r 
INNER JOIN 
       drivers d ON d.driverId = r.driverId
INNER JOIN 
     races s ON s.raceId = r.raceId
WHERE 
       r.position IN (1, 2, 3) AND
	   s.year = 2016
GROUP BY
       d.driverId, 
	   d.forename, d.surname
ORDER BY Cantidad_Podios DESC
LIMIT 3;"

Podios_2016 <- dbGetQuery(con, Podios_2016) 

```

```{r}
## 2017 ##

Podios_2017 <- "SELECT d.driverId AS ID_Pilotos,
       d.forename AS Nombre,
       d.surname AS Apellido,
       s.year AS temporada,   
       SUM(CASE WHEN r.position = 1 THEN 1 ELSE 0 END) AS Podios_1,
       SUM(CASE WHEN r.position = 2 THEN 1 ELSE 0 END) AS Podios_2,
       SUM(CASE WHEN r.position = 3 THEN 1 ELSE 0 END) AS Podios_3,
       COUNT(r.position) AS Cantidad_Podios
FROM  
       results r 
INNER JOIN 
       drivers d ON d.driverId = r.driverId
INNER JOIN 
     races s ON s.raceId = r.raceId
WHERE 
       r.position IN (1, 2, 3) AND
	   s.year = 2017
GROUP BY
       d.driverId, 
	   d.forename, d.surname
ORDER BY Cantidad_Podios DESC
LIMIT 3;"

Podios_2017 <- dbGetQuery(con, Podios_2017) 

```

```{r}
## Número DE RETIROS POR FALLAS MECANICAS y PARADAS EN LOS BOXES EN EL AÑO 2017 ##

Retiro_Fallas_Parada_boxes_2017 <- "SELECT r.year AS Año,
       r.name AS carrera,
       d.forename || ' ' || d.surname AS Piloto,
	   SUM(e.points) AS Total_Puntos,
	   SUM(e.wins) AS Total_Victoias,
       COUNT(DISTINCT CASE WHEN s.status like '%Mechanical%' OR '%Electrical%' OR '%Engine misfire%' OR '%Engine fire%'  THEN res.resultId END) AS retiros_por_fallas_mecanicas,
       COUNT(DISTINCT ps.stop) AS paradas_en_boxes
FROM drivers d INNER JOIN results res ON d.driverId = res.driverId
INNER JOIN driver_standings e ON d.driverId = e.driverId
INNER JOIN races r ON res.raceId = r.raceId
LEFT JOIN status s ON res.statusId = s.statusId
LEFT JOIN pitstops ps ON d.driverId = ps.driverId AND r.raceId = ps.raceId
WHERE r.year == 2017
GROUP BY d.driverId, r.raceId
ORDER BY paradas_en_boxes AND retiros_por_fallas_mecanicas AND Total_Puntos DESC;"

Retiro_Fallas_Parada_boxes_2017 <- dbGetQuery(con, Retiro_Fallas_Parada_boxes_2017)
```

```{r}
## Número DE RETIROS POR FALLAS MECANICAS y PARADAS EN LOS BOXES EN EL AÑO 2016 ##

Retiro_Fallas_Parada_boxes_2016 <- "SELECT r.year AS Año,
       r.name AS carrera,
       d.forename || ' ' || d.surname AS Piloto,
	   SUM(e.points) AS Total_Puntos,
	   SUM(e.wins) AS Total_Victoias,
       COUNT(DISTINCT CASE WHEN s.status like '%Mechanical%' OR '%Electrical%' OR '%Engine misfire%' OR '%Engine fire%'  THEN res.resultId END) AS retiros_por_fallas_mecanicas,
       COUNT(DISTINCT ps.stop) AS paradas_en_boxes
FROM drivers d INNER JOIN results res ON d.driverId = res.driverId
INNER JOIN driver_standings e ON d.driverId = e.driverId
INNER JOIN races r ON res.raceId = r.raceId
LEFT JOIN status s ON res.statusId = s.statusId
LEFT JOIN pitstops ps ON d.driverId = ps.driverId AND r.raceId = ps.raceId
WHERE r.year == 2016
GROUP BY d.driverId, r.raceId
ORDER BY paradas_en_boxes AND retiros_por_fallas_mecanicas AND Total_Puntos DESC;"

Retiro_Fallas_Parada_boxes_2016 <- dbGetQuery(con, Retiro_Fallas_Parada_boxes_2016)
```


```{r}
## Número DE RETIROS POR FALLAS MECANICAS y PARADAS EN LOS BOXES EN EL AÑO 2015 ##

Retiro_Fallas_Parada_boxes_2015 <- "SELECT r.year AS Año,
       r.name AS carrera,
       d.forename || ' ' || d.surname AS Piloto,
	   SUM(e.points) AS Total_Puntos,
	   SUM(e.wins) AS Total_Victoias,
       COUNT(DISTINCT CASE WHEN s.status like '%Mechanical%' OR '%Electrical%' OR '%Engine misfire%' OR '%Engine fire%'  THEN res.resultId END) AS retiros_por_fallas_mecanicas,
       COUNT(DISTINCT ps.stop) AS paradas_en_boxes
FROM drivers d INNER JOIN results res ON d.driverId = res.driverId
INNER JOIN driver_standings e ON d.driverId = e.driverId
INNER JOIN races r ON res.raceId = r.raceId
LEFT JOIN status s ON res.statusId = s.statusId
LEFT JOIN pitstops ps ON d.driverId = ps.driverId AND r.raceId = ps.raceId
WHERE r.year == 2015
GROUP BY d.driverId, r.raceId
ORDER BY paradas_en_boxes AND retiros_por_fallas_mecanicas AND Total_Puntos DESC;"

Retiro_Fallas_Parada_boxes_2015 <- dbGetQuery(con, Retiro_Fallas_Parada_boxes_2015)
```


```{r}
## Número DE RETIROS POR FALLAS MECANICAS y PARADAS EN LOS BOXES EN EL AÑO 2014

Retiro_Fallas_Parada_boxes_2014 <- "SELECT r.year AS Año,
       r.name AS carrera,
       d.forename || ' ' || d.surname AS Piloto,
	   SUM(e.points) AS Total_Puntos,
	   SUM(e.wins) AS Total_Victoias,
       COUNT(DISTINCT CASE WHEN s.status like '%Mechanical%' OR '%Electrical%' OR '%Engine misfire%' OR '%Engine fire%'  THEN res.resultId END) AS retiros_por_fallas_mecanicas,
       COUNT(DISTINCT ps.stop) AS paradas_en_boxes
FROM drivers d INNER JOIN results res ON d.driverId = res.driverId
INNER JOIN driver_standings e ON d.driverId = e.driverId
INNER JOIN races r ON res.raceId = r.raceId
LEFT JOIN status s ON res.statusId = s.statusId
LEFT JOIN pitstops ps ON d.driverId = ps.driverId AND r.raceId = ps.raceId
WHERE r.year == 2014
GROUP BY d.driverId, r.raceId
ORDER BY paradas_en_boxes AND retiros_por_fallas_mecanicas AND Total_Puntos DESC;"

Retiro_Fallas_Parada_boxes_2014 <- dbGetQuery(con, Retiro_Fallas_Parada_boxes_2014)
```


```{r}
## Número DE RETIROS POR FALLAS MECANICAS y PARADAS EN LOS BOXES EN EL AÑO 2013 ##

Retiro_Fallas_Parada_boxes_2013 <- "SELECT r.year AS Año,
       r.name AS carrera,
       d.forename || ' ' || d.surname AS Piloto,
	   SUM(e.points) AS Total_Puntos,
	   SUM(e.wins) AS Total_Victoias,
       COUNT(DISTINCT CASE WHEN s.status like '%Mechanical%' OR '%Electrical%' OR '%Engine misfire%' OR '%Engine fire%'  THEN res.resultId END) AS retiros_por_fallas_mecanicas,
       COUNT(DISTINCT ps.stop) AS paradas_en_boxes
FROM drivers d INNER JOIN results res ON d.driverId = res.driverId
INNER JOIN driver_standings e ON d.driverId = e.driverId
INNER JOIN races r ON res.raceId = r.raceId
LEFT JOIN status s ON res.statusId = s.statusId
LEFT JOIN pitstops ps ON d.driverId = ps.driverId AND r.raceId = ps.raceId
WHERE r.year == 2013
GROUP BY d.driverId, r.raceId
ORDER BY paradas_en_boxes AND retiros_por_fallas_mecanicas AND Total_Puntos DESC;"

Retiro_Fallas_Parada_boxes_2013 <- dbGetQuery(con, Retiro_Fallas_Parada_boxes_2013)
```